package plugins

import (
	"fmt"
	"testing"

	"github.com/quintans/gog/config"
)

func TestRequiredArgsConstructor(t *testing.T) {
	tests := []struct {
		name string
		in   string
		out  string
	}{
		{
			"RequiredArgsConstructor_1_required",
			`
package p

// gog:requiredArgsConstructor
type Foo struct {
	// gog:@required
	name  string
	value int64
}
`,
			fmt.Sprintf(`// Code generated by gog; DO NOT EDIT.
// Version: %s
package p

// Generated by gog:requiredArgsConstructor

func NewFooRequired(name string) Foo {
	return Foo{
		name: name,
	}
}
`, config.Version),
		},
		{
			"RequiredArgsConstructor_many_required",
			`
package p

// gog:requiredArgsConstructor
type Foo struct {
	// gog:@required
	name  string
	// gog:@required
	value int64
}
`,
			fmt.Sprintf(`// Code generated by gog; DO NOT EDIT.
// Version: %s
package p

// Generated by gog:requiredArgsConstructor

func NewFooRequired(name string, value int64) Foo {
	return Foo{
		name:  name,
		value: value,
	}
}
`, config.Version),
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			run(t, tt.in, tt.out)
		})
	}
}
